### ISSUE TITLE
Broken due to breaking changes in `ezkl_lib`

### ISSUE THREAD

**Issue by georgwiese** [zkonduit/pyezkl#32]
The `zkml` package imports `forward`, which doesn't exist in `ezkl_lib == 0.3.0`. Since it requires `ezkl_lib = ">=0.1.0"` the package manager won't catch that, so I think the quick fix would be to restrict `ezkl_lib` to an earlier version!

Basically running `pip install ezkl` in a fresh environment and then `import ezkl` fails right now.

**Comment by JSeam2** [comment]
This should be resolved in https://github.com/zkonduit/pyezkl/pull/31 which will be merged soon

Do note that `forward` has been renamed to `gen-witness`

**Comment by JSeam2** [comment]
Closing as #31 has been merged. Do reopen the issue if similar problems persist.
